---
spring:
  application:
    name: crudoperations
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        serviceId: SAMPLE-HYSTRIX-CONFIG

eureka:
  instance:
    nonSecurePort: ${server.port:8089}
  client:
    serviceUrl:
      defaultZone: http://35.168.21.233:8761/eureka
